In [1]:
!pip install datasets transformers evaluate seqeval

Requirement already satisfied: datasets in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (4.8.4)
Requirement already satisfied: transformers in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (5.5.0)
Requirement already satisfied: evaluate in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (0.4.6)
Requirement already satisfied: seqeval in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.2.2)
Requirement already satisfied: filelock in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (2.4.1)
Requirement already satisfied: pyarrow>=21.0.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (1.8.0)
Requirement already satisfied: packaging in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.2)
Requirement already satisfied: typer in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: regex>=2025.10.22 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: scikit-learn>=0.21.3 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from seqeval) (1.8.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: scipy>=1.10.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn>=0.21.3->seqeval) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn>=0.21.3->seqeval) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from scikit-learn>=0.21.3->seqeval) (3.6.0)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python312\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Roaming\Python\Python312\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)

In [2]:
from transformers import TrainingArguments

C:\Users\Samyagh\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    pipeline,
    DataCollatorForTokenClassification
)
import numpy as np
import evaluate

In [4]:
dataset = load_dataset("lhoestq/conll2003")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
label_column = "pos_tags"

In [6]:
# label_column = "chunk_tags"

In [7]:
# Select task
label_column = "pos_tags"   # change to "chunk_tags" for chunking

# Define labels manually (based on dataset)
if label_column == "pos_tags":
    label_names = [
        '"', "''", '#', '$', '(', ')', ',', '.', ':', '``',
        'CC', 'CD', 'DT', 'EX', 'FW', 'IN', 'JJ', 'JJR', 'JJS',
        'LS', 'MD', 'NN', 'NNP', 'NNPS', 'NNS', 'NN|SYM', 'PDT',
        'POS', 'PRP', 'PRP$', 'RB', 'RBR', 'RBS', 'RP', 'SYM',
        'TO', 'UH', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ',
        'WDT', 'WP', 'WP$', 'WRB'
    ]

elif label_column == "chunk_tags":
    label_names = [
        'O','B-ADJP','I-ADJP','B-ADVP','I-ADVP','B-CONJP','I-CONJP',
        'B-INTJ','I-INTJ','B-LST','I-LST','B-NP','I-NP','B-PP',
        'I-PP','B-PRT','I-PRT','B-SBAR','I-SBAR','B-UCP','I-UCP',
        'B-VP','I-VP'
    ]

# Create mappings
id2label = {i: label for i, label in enumerate(label_names)}
label2id = {label: i for i, label in enumerate(label_names)}
num_labels = len(label_names)

In [8]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [9]:
def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(
        examples["tokens"],
        truncation=True,
        padding="max_length",
        max_length=32, 
        is_split_into_words=True
    )

    labels = []
    for i, label in enumerate(examples[label_column]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        label_ids = []
        prev = None

        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != prev:
                label_ids.append(label[word_idx])
            else:
                label_ids.append(-100)
            prev = word_idx

        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

tokenized_dataset = dataset.map(tokenize_and_align_labels, batched=True)

Map: 100%|██████████████████████████████████████████████████████████████| 14041/14041 [00:02<00:00, 6027.40 examples/s]
Map: 100%|████████████████████████████████████████████████████████████████| 3250/3250 [00:00<00:00, 6417.20 examples/s]
Map: 100%|████████████████████████████████████████████████████████████████| 3453/3453 [00:00<00:00, 6634.36 examples/s]

In [10]:
train_dataset = tokenized_dataset["train"].select(range(800))
eval_dataset = tokenized_dataset["validation"].select(range(200))

In [11]:
model = AutoModelForTokenClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id
)

Loading weights: 100%|█████████████████████████████████████████████████████████████| 197/197 [00:00<00:00, 4023.32it/s]
BertForTokenClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [12]:
data_collator = DataCollatorForTokenClassification(tokenizer)

In [13]:
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="no",
    learning_rate=5e-5,
    num_train_epochs=1,
    per_device_train_batch_size=4
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=data_collator
)

trainer.train()

C:\Users\Samyagh\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.79it/s]

TrainOutput(global_step=200, training_loss=1.2845556640625, metrics={'train_runtime': 158.8275, 'train_samples_per_second': 5.037, 'train_steps_per_second': 1.259, 'total_flos': 13070153164800.0, 'train_loss': 1.2845556640625, 'epoch': 1.0})

In [15]:
import evaluate
import numpy as np

# Load metric
metric = evaluate.load("seqeval")

# Define compute_metrics
def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = [
        [id2label[p] for (p, l) in zip(pred, lab) if l != -100]
        for pred, lab in zip(predictions, labels)
    ]

    true_labels = [
        [id2label[l] for (p, l) in zip(pred, lab) if l != -100]
        for pred, lab in zip(predictions, labels)
    ]

    return metric.compute(
        predictions=true_predictions,
        references=true_labels
    )

# ✅ FINAL TRAINER (IMPORTANT FIX)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics   # 🔥 ADD HERE
)

# ✅ ONLY RUN THIS
trainer.train()

Writing model shards: 100%|██████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.05it/s]

TrainOutput(global_step=200, training_loss=0.40630409240722654, metrics={'train_runtime': 157.3247, 'train_samples_per_second': 5.085, 'train_steps_per_second': 1.271, 'total_flos': 13070153164800.0, 'train_loss': 0.40630409240722654, 'epoch': 1.0})

In [16]:
nlp = pipeline("token-classification", model=model, tokenizer=tokenizer)

sentence = "John works at Google in California"

output = nlp(sentence)

for token in output:
    print(token["word"], token["entity"])

john NNP
works VBZ
at NNP
google NNP
in IN
california NNP